# -*- coding: utf-8 -*-
"""combination

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZSA3FTPk3t5NxZSl53SHlIK-YlA6DRqn
"""

pip install pymongo openai

pip install --upgrade --upgrade-strategy eager "regex" "charset-normalizer<4" "idna" "urllib3<3" "certifi" "requests" "anyio<5" "distro<2" "sniffio" "h11<0.15" "httpcore==1.*" "annotated-types" "typing-extensions<5" "pydantic-core==2.27.1" "pydantic<3" "jiter<1" "tqdm" "colorama" "openai" "tiktoken" "httpx<0.28"

# @title 1. 검색 결과(가정)
from pymongo import MongoClient

# MongoDB 클러스터 연결
client = MongoClient("[connection_string]")
db = client['address']

from pymongo import MongoClient

# 테이블별로 카테고리 데이터를 검색
def fetch_items_from_collections(db, collections, categories):
    all_data = {}

    for collection_name, category_list in collections.items():
        collection = db[collection_name]
        all_data[collection_name] = {}

        for category in category_list:
            # Aggregation Pipeline
            pipeline = [
                {"$match": {"category": category}},  # 카테고리 필터링
                {"$project": {"_id":0, "imageUrl": 1, "category": 1}},  # 필요한 필드만 포함
                {"$limit": 2} # 최대 3개 제한
            ]

            # Aggregation 실행
            results = collection.aggregate(pipeline)
            all_data[collection_name][category] = list(results)  # 결과를 리스트로 변환

    return all_data

# 테이블 및 카테고리 정의
collections = {
    "top": ["맨투맨", "셔츠&블라우스", "후드 티셔츠", "니트", "긴소매 티셔츠", "반소매 티셔츠", "민소매 티셔츠"],
    "pants": ["데님 팬츠", "코튼 팬츠", "슬랙스", "트레이닝 팬츠", "숏팬츠", "레깅스"],
    "dress": ["미니원피스", "미디원피스", "맥시원피스"],
    "skirt": ["미니스커트", "미디스커트", "롱스커트"],
    "outer": ["패딩", "플리스", "코트", "자켓", "점퍼", "블레이저", "가디건", "바람막이"]
}


    # 데이터 검색 출력
all_categorized_data = fetch_items_from_collections(db, collections, collections)
#print(all_categorized_data)
for collection, categories in all_categorized_data.items():
    print(f"Collection: {collection}")
    for category, items in categories.items():
        print(f"  Category: {category} - Number of items: {len(items)}")
        for item in items:
            print(f"    Data: {item}")

#@title 2.사용자 입력 (가정)
# 사용자로부터 스타일 입력받기
user_style = input("원하는 스타일을 선택해주세요 (캐주얼)(모던/시크/미니멀)(걸리시)(스트릿)(빈티지)(클래식): ")

# @title 3.스타일 입력에 따라 어울리는 카테고리 설계
import openai
import json
# OpenAI API 키 설정
client = openai.OpenAI(api_key="[api_key]")
# 스타일에 따라 조합할 카테고리 리스트 정의
style_items = {
    "캐주얼": {
        "상의": ["맨투맨", "후드 티셔츠", "니트", "긴소매 티셔츠", "반소매 티셔츠"],
        "바지": ["데님 팬츠", "트레이닝 팬츠", "코튼 팬츠", "숏팬츠", "레깅스"],
        "아우터": ["바람막이", "점퍼", "플리스", "가디건", "자켓"]
    },
    "모던/시크/미니멀": {
        "상의": ["셔츠&블라우스", "니트", "긴소매 티셔츠", "반소매 티셔츠"],
        "바지": ["슬랙스"],
        "치마": ["미디스커트", "롱스커트"],
        "아우터": ["코트", "블레이저", "자켓"]
    },
    "걸리시": {
        "상의": ["셔츠&블라우스", "긴소매 티셔츠", "니트", "민소매 티셔츠"],
        "치마": ["미니스커트", "미디스커트", "롱스커트"],
        "원피스": ["미니원피스", "미디원피스"],
        "아우터": ["가디건", "코트"]
    },
    "스트릿": {
        "상의": ["맨투맨", "후드 티셔츠", "긴소매 티셔츠", "반소매 티셔츠"],
        "바지": ["데님 팬츠", "트레이닝 팬츠", "코튼 팬츠", "레깅스"],
        "아우터": ["점퍼", "바람막이", "플리스"]
    },
    "빈티지": {
        "상의": ["셔츠&블라우스", "니트", "긴소매 티셔츠", "민소매 티셔츠"],
        "치마": ["롱스커트", "체크 스커트"],
        "바지": ["코튼 팬츠"],
        "원피스": ["미디원피스", "미니원피스"],
        "아우터": ["가디건", "자켓", "코트"]
    },
    "클래식": {
        "상의": ["셔츠&블라우스", "니트", "긴소매 티셔츠"],
        "치마": ["롱스커트", "미디스커트"],
        "바지":["슬랙스"],
        "원피스": ["미디원피스"],
        "아우터": ["코트", "블레이저", "가디건"]
    }
}

def filter_items_by_style(user_style, categorized_data, style_items):
    # 결과를 저장할 딕셔너리
    filtered_data = {}

    # 스타일별 유효 카테고리를 가져옵니다.
    if user_style not in style_items:
        raise ValueError(f"Invalid style '{user_style}'. Please choose a valid style.")

    # 스타일별 카테고리 매핑
    style_categories = style_items[user_style]

    # 스타일 카테고리를 순회하며 데이터 필터링
    for category_type, valid_categories in style_categories.items():
        if category_type not in filtered_data:
            filtered_data[category_type] = []  # 초기화

        # categorized_data에서 해당 카테고리를 찾음
        db_category_key = None
        if category_type == "상의":
            db_category_key = "top"
        elif category_type == "바지":
            db_category_key = "pants"
        elif category_type == "치마":
            db_category_key = "skirt"
        elif category_type == "원피스":
            db_category_key = "dress"
        elif category_type == "아우터":
            db_category_key = "outer"

        if db_category_key and db_category_key in categorized_data:
            # 해당 데이터베이스 카테고리에서 유효한 카테고리를 필터링
            for valid_category in valid_categories:
                if valid_category in categorized_data[db_category_key]:
                    filtered_data[category_type].extend(
                        categorized_data[db_category_key][valid_category]
                    )

    return filtered_data


filtered_items = filter_items_by_style(user_style, all_categorized_data, style_items)

all_image_urls = [
    item["imageUrl"]
    for items in filtered_items.values()
    for item in items
    if "imageUrl" in item
]

# 세부 카테고리만 리스트에 저장
filtered_detailed_categories = [
    item["category"]
    for items in filtered_items.values()
    for item in items
    if "category" in item
]

for category_type, items in filtered_items.items():
    print(f"\n==== {category_type} (총 {len(items)}개) ====")
    for item in items:
        print(f"Category: {item['category']}\nImage URL: {item['imageUrl']}\n")

# @title 4.스타일에 따른 두드러지는 특징 정의
style_features = [
    {
        "style": "캐주얼",
        "features": {
            "색상": "밝고 산뜻한 색상 또는 기본적인 베이직 컬러(흰색, 회색, 네이비 등)",
            "핏": "여유롭고 편안한 핏(루즈핏, 오버핏)",
            "소재": "편안하고 부드러운 소재(면, 플리스, 스웨트)",
            "패턴": "심플한 로고, 스트라이프, 그래픽 프린트"
        }
    },
    {
        "style": "모던/시크/미니멀",
        "features": {
            "색상": "무채색 계열(검정, 흰색, 회색, 베이지)",
            "핏": "정핏 또는 세미 오버핏으로 깔끔한 실루엣",
            "소재": "고급스러운 소재(울, 캐시미어, 실크)",
            "패턴": "패턴 없는 솔리드 컬러 또는 간결한 체크, 스트라이프"
        }
    },
    {
        "style": "걸리시",
        "features": {
            "색상": "핑크, 파스텔톤, 화사한 색상",
            "핏": "타이트하거나 허리를 강조하는 실루엣",
            "소재": "레이스, 쉬폰, 니트 등 부드럽고 여성스러운 소재",
            "패턴": "도트, 플로럴 프린트, 프릴 디테일"
        }
    },
    {
        "style": "스트릿",
        "features": {
            "색상": "강렬한 색상(레드, 블랙, 네온) 또는 컬러 블록 조합",
            "핏": "오버핏 상의와 하의",
            "소재": "나일론, 데님, 플리스",
            "패턴": "그래픽 프린트, 브랜드 로고, 타이다이"
        }
    },
    {
        "style": "빈티지",
        "features": {
            "색상": "톤 다운된 컬러(버건디, 올리브, 브라운, 머스터드)",
            "핏": "여유롭고 자연스러운 핏",
            "소재": "코듀로이, 트위드, 니트",
            "패턴": "체크, 플로럴 프린트, 레트로 디자인"
        }
    },
    {
        "style": "클래식",
        "features": {
            "색상": "차분하고 고급스러운 색상(네이비, 블랙, 화이트, 베이지)",
            "핏": "정핏으로 몸을 단정하게 잡아주는 실루엣",
            "소재": "고급스러운 소재(울, 실크, 트위드)",
            "패턴": "스트라이프, 하운드투스 체크"
        }
    }
]

#@title 5. gpt api를 호출하여 코디 조합 요청
messageMaker = [{"type":"text", "text":f"""Based on the given style '{user_style}', recommend 5 outfits using ONLY the provided image URLs.
    The distinctive features of each style are as follows. Please reflect these as much as possible when recommending outfits: {style_features}
    Please provide explanations why these outfits are suitable for the given style. Please explain what kinds of shoes, bags, or accessories would be matching with each combination.
    Do not create, modify, or add any other URLs.
    Use the exact URLs listed below as part of your response.
    Let's assume that I didn't provide these URLs, but you had them from the beginning.
    Please include the image URLs in the recommendations.
    You can ONLY provide outfit combinations among the following options:
    1. Top + Pants + Outerwear
    2. Top + Skirt + Outerwear
    3. Dress + Outerwear
    Make sure you translate the answer to Korean."""}]

for url in all_image_urls:
    messageMaker.append({"type": "image_url", "image_url": {"url": url}})
    messageMaker.append({"type": "text", "text": "image url: "+url})

def generate_outfit_with_style(messageMaker):
    # OpenAI API 호출
    response = client.chat.completions.create(
        model="gpt-4o",
        messages=[{"role": "user", "content": messageMaker}]
    )
    # 결과 반환
    return response.choices[0].message.content  # .content로 수정

# 결과 생성
result = generate_outfit_with_style(messageMaker)

# 결과 출력
print(result)